<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AmeliorerPresentation.aspx.cs" Inherits="DropDown.AmeliorerPresentation" StylesheetTheme="Style" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
   <p><asp:Label ID="Label7" runat="server" Text="Vous avez appuyez sur : "></asp:Label><asp:Label ID="LabelCommandName" runat="server" Text=""></asp:Label></p>
    <p><asp:Label ID="Label5" runat="server" Text="Vous êtes sur la ligne : "></asp:Label><asp:Label ID="LabelCommandArgument" runat="server" Text=""></asp:Label></p>
     <asp:Label runat="server" Text="" ID="LabelErreur" ForeColor="#CC0000"></asp:Label>
    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ProductID" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowCommand="GridView1_RowCommand" CssClass="table table-striped table-condensed table-responsive table-bordered" CellPadding="2" CellSpacing="8" Width="100%" BorderStyle="None" EditRowStyle-ForeColor="#009933">
        <Columns>

            <asp:BoundField DataField="ProductID" HeaderText="ProductID" ReadOnly="True" InsertVisible="False" SortExpression="ProductID"></asp:BoundField>
            <asp:TemplateField HeaderText="Nom Produit" SortExpression="ProductName">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("ProductName") %>' ID="TextBoxProductName" AutoCompleteType="Enabled" AutoPostBack="False" CausesValidation="True"></asp:TextBox>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidatorProductName" runat="server" ErrorMessage="Le champs doit contenir des lettres" Text="Le champs doit contenir des lettres" ControlToValidate="TextBoxProductName" Display="Dynamic" ValidationExpression="^[a-zA-Z]{1,40}$"></asp:RegularExpressionValidator>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidatoProductname" runat="server" ErrorMessage="Le champs produit est obligatoire" Text="Champs est obligatoire" Display="Dynamic" ControlToValidate="TextBoxProductName"></asp:RequiredFieldValidator>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("ProductName") %>' ID="Label3"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Fournisseur" SortExpression="SupplierID">
                <EditItemTemplate>
                    <asp:DropDownList ID="Fournisseur1" runat="server" DataSourceID="SqlDataSourceSuppliers" DataTextField="CompanyName" DataValueField="SupplierID" SelectedValue='<%# Bind("SupplierID") %>'></asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# CategorieName(SqlDataSourceSuppliers, (System.Data.DataRowView)Container.DataItem, "SupplierID", "CompanyName") %>' ID="Label2"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="CategoryID" SortExpression="CategoryID">
                <EditItemTemplate>
                    <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSourceCategories" DataTextField="CategoryName" DataValueField="CategoryID" SelectedValue='<%# Bind("CategoryID") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# CategorieName(SqlDataSourceCategories, (System.Data.DataRowView)Container.DataItem, "CategoryID", "CategoryName" ) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Nombre par unit" SortExpression="QuantityPerUnit">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("QuantityPerUnit") %>' ID="TextBoxQPU" MaxLength="20" AutoPostBack="False"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidatorQPU" runat="server" ErrorMessage="Le champs quantity per unit est obligatoire" Text="Champs est obligatoire" Display="Dynamic" ControlToValidate="TextBoxQPU"> </asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidatorQPU" runat="server" ErrorMessage="Le nombre de lettres ne peut pas dépasser 20" Text="Ne depassez pas les 20 caractères" Display="Dynamic" ControlToValidate="TextBoxQPU" ValidationExpression="^[a-zA-Z0-9]{1,20}$"> </asp:RegularExpressionValidator>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("QuantityPerUnit") %>' ID="Label4"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" DataFormatString="{0:C}"></asp:BoundField>
            <asp:TemplateField HeaderText="UnitsInStock" SortExpression="UnitsInStock">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("UnitsInStock") %>' ID="TextBox1"></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("UnitsInStock") %>' ID="Label5"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:BoundField DataField="UnitsOnOrder" HeaderText="UnitsOnOrder" SortExpression="UnitsOnOrder"></asp:BoundField>
            <asp:BoundField DataField="ReorderLevel" HeaderText="ReorderLevel" SortExpression="ReorderLevel"></asp:BoundField>
            <asp:CheckBoxField DataField="Discontinued" HeaderText="Discontinued" SortExpression="Discontinued"></asp:CheckBoxField>
            <asp:BoundField DataField="UnitsReserved" HeaderText="UnitsReserved" SortExpression="UnitsReserved"></asp:BoundField>
            <asp:TemplateField></asp:TemplateField>
         
            <asp:HyperLinkField DataNavigateUrlFields="ProductID" DataNavigateUrlFormatString="DetailsViewInserted.aspx?ProductID={0}" Text="Ins&#233;rer" HeaderText="Ins&#233;rer"></asp:HyperLinkField>
        </Columns>
        <EditRowStyle BorderStyle="None" />
        <RowStyle BorderStyle="None" />
    </asp:GridView>
   
    <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" DataSourceID="SqlDataSource1">
        <Fields>
             <asp:TemplateField HeaderText="UnitsInStock" SortExpression="UnitsInStock">
                <InsertItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("UnitsInStock") %>' ID="TextBoxUIS"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="RequiredFieldValidator" Display="Dynamic" ControlToValidate="TextBoxUIS"></asp:RequiredFieldValidator>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("UnitsInStock") %>' ID="Label5"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:CommandField ShowInsertButton="True"></asp:CommandField>
        </Fields>
    </asp:DetailsView>
    
    <asp:SqlDataSource ID="SqlDataSourceProductName" runat="server" ConnectionString='<%$ ConnectionStrings:ComptoirAnglais_V1 %>' SelectCommand="SELECT DISTINCT [ProductName] FROM [Products]"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceSuppliers" runat="server" ConnectionString='<%$ ConnectionStrings:ComptoirAnglais_V1 %>' SelectCommand="SELECT [SupplierID], [CompanyName] FROM [Suppliers]"></asp:SqlDataSource>
      <asp:SqlDataSource ID="SqlDataSourceCategories" runat="server" ConnectionString="<%$ ConnectionStrings:ComptoirAnglais_V1 %>" SelectCommand="SELECT [CategoryID], [CategoryName] FROM [Categories]"></asp:SqlDataSource>
                
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString='<%$ ConnectionStrings:ComptoirAnglais_V1 %>' SelectCommand="SELECT * FROM [Products]" InsertCommand="INSERT INTO [Products] ([ProductName], [SupplierID], [CategoryID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [UnitsReserved]) VALUES (@ProductName, @SupplierID, @CategoryID, @QuantityPerUnit, @UnitPrice, @UnitsInStock, @UnitsOnOrder, @ReorderLevel, @Discontinued, @UnitsReserved)" ondeleted="SqlDataSource1_Deleted" DeleteCommand="DELETE FROM [Products] WHERE [ProductID] = @ProductID" UpdateCommand="UPDATE [Products] SET [ProductName] = @ProductName, [SupplierID] = @SupplierID, [CategoryID] = @CategoryID, [QuantityPerUnit] = @QuantityPerUnit, [UnitPrice] = @UnitPrice, [UnitsInStock] = @UnitsInStock, [UnitsOnOrder] = @UnitsOnOrder, [ReorderLevel] = @ReorderLevel, [Discontinued] = @Discontinued, [UnitsReserved] = @UnitsReserved WHERE [ProductID] = @ProductID"> <DeleteParameters>
            <asp:Parameter Name="ProductID" Type="Int32" />
        </DeleteParameters>
       
        <InsertParameters>
            <asp:Parameter Name="ProductName" Type="String" />
            <asp:Parameter Name="SupplierID" Type="Int32" />
            <asp:Parameter Name="CategoryID" Type="Int32" />
            <asp:Parameter Name="QuantityPerUnit" Type="String" />
            <asp:Parameter Name="UnitPrice" Type="Decimal" />
            <asp:Parameter Name="UnitsInStock" Type="Int16" />
            <asp:Parameter Name="UnitsOnOrder" Type="Int16" />
            <asp:Parameter Name="ReorderLevel" Type="Int16" />
            <asp:Parameter Name="Discontinued" Type="Boolean" />
            <asp:Parameter Name="UnitsReserved" Type="Int32" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="ProductName" Type="String" />
            <asp:Parameter Name="SupplierID" Type="Int32" />
            <asp:Parameter Name="CategoryID" Type="Int32" />
            <asp:Parameter Name="QuantityPerUnit" Type="String" />
            <asp:Parameter Name="UnitPrice" Type="Decimal" />
            <asp:Parameter Name="UnitsInStock" Type="Int16" />
            <asp:Parameter Name="UnitsOnOrder" Type="Int16" />
            <asp:Parameter Name="ReorderLevel" Type="Int16" />
            <asp:Parameter Name="Discontinued" Type="Boolean" />
            <asp:Parameter Name="UnitsReserved" Type="Int32" />
            <asp:Parameter Name="ProductID" Type="Int32" />
        </UpdateParameters> </asp:SqlDataSource>

     <asp:SqlDataSource runat="server"></asp:SqlDataSource>
     <asp:ValidationSummary ID="ValidationSummary1" runat="server" HeaderText="Erreurs" ShowMessageBox="True" />

</asp:Content>
